### ISSUE TITLE
{status.online.players} not displaying as int

### ISSUE THREAD

**Issue by nephazine** [py-mine/mcstatus#217]
https://gyazo.com/7de7f5c575233e5e3eb910000fe88d0c

{status.online.players} isn't displaying an integer, instead displays the word.

**Comment by ItsDrike** [comment]
I don't quite follow. Could you elaborate on this? Perhaps give us an actual minimal reproducable example with code shoing the issue?

I'm not aware of `status.online.players` being a thing, our `mcstatus.pinger.PingResponse` class has `players.online` attribute, not `online.players`, and the `mcstatus.querier.QueryResponse` also only has `players.online`, not `online.players`. And those attributes both store an integer value, not a string.


![Screenshot_2022-02-21_14-25-19](https://user-images.githubusercontent.com/20902250/154964079-9991c9fa-67ac-4c5e-8801-4552caef43b1.png)

**Comment by kevinkjt2000** [comment]
Sounds like `f` was forgotten to make the string a format string.
