### ISSUE TITLE
Consider force defining pyright's version

### ISSUE THREAD

**Issue by ItsDrike** [py-mine/mcstatus#233]
Because our project relies on the [pyright python package](https://pypi.org/project/pyright/) listed as a development dependency, which automatically installs the latest version of pyright into the virtual environment, we may face some unexpected typing failures as new pyright versions are released, which is precisely what already happened in #232.

Because of this, it's possible that our Validation workflow will randomly fail on previously passing code, without any apparent reason. This can be annoying, especially for new contributors who don't know that this could happen, because they may see the workflow fail on their PRs, telling them to fix code they didn't even touch.

A possible solution to this would be to hard-code the pyright's version for the python pyright dependency into the workflow directly, using the `PYRIGHT_PYTHON_FORCE_VERSION` environmental variable. However if we do decide to go this way, it would mean we'd need to actively monitor new pyright's releases to make sure that we update the workflow when needed and bump the defined version in it manually. This can be very annoying though, so it may not be worth doing.

Even if we do decide to do this and hard-code the version in the workflow, it doesn't change anything about people's local config, which means if they'd run pyright, installed by the python pyright package, these unexpected errors could still appear to them, even though the workflows on github would pass. I'm not entirely sure how this could be addressed, other than documenting that they should be setting this variable in `CONTRIBUTING.md`.

**Comment by RobertCraigie** [comment]
This behaviour has been changed in the latest release. The pyright python package no longer automatically installs the latest version of pyright by default and is pinned to a specific version of pyright.

It is highly recommended that you enable an automatic dependency bot such as dependabot so that you will get PRs to bump the pyright version.

**Comment by kevinkjt2000** [comment]
Of course, `tox -e lint` could set an environment variable to be used by CI and devs. Seeing as how the lock file already pins the python dependencies and the good news about pyright python pinning the pyright npm, updating pyright python should be the way to go here with automated dependency updates rolling in on occasion.

**Comment by ItsDrike** [comment]
> Of course, `tox -e lint` could set an environment variable to be used by CI and devs

Oh right, I didn't think of that, I'm used to running pyright with `poetry run pyright` which is probably why.

> Seeing as how the lock file already pins the python dependencies and the good news about pyright python pinning the pyright npm, updating pyright python should be the way to go here with automated dependency updates rolling in on occasion.

Certainly, it was a very recent update to python-pyright which added this, and it's a really good addition (thanks @RobertCraigie). I've also already linked a PR which closes this and adds dependabot as suggested.
