### ISSUE TITLE
Forge servers not supported?

### ISSUE THREAD

**Issue by SuperKali** [py-mine/mcstatus#252]
Hi,

I created a discord status bot with this library, but it seems that the forge servers are not responding to the query, I get this warning:
`OSError: Server did not respond with any information!`

There are some issue about it?

**Comment by kevinkjt2000** [comment]
Query requires enabling in server.properties and opening UDP port in any firewall(s). This is up to you, not mcstatus.

Ref #164

**Comment by SuperKali** [comment]
All server response to the query without problem, only forge server have this problem.

**Comment by kevinkjt2000** [comment]
Then, only this forge server has a firewall blocking it or query is disabled in its server.properties. This is not a problem for mcstatus. Check the things I have mentioned and your issue should disappear. It's not up to us to fix your firewalls and server.properties, sorry / not sorry.
