### ISSUE TITLE
getting scoreboard data

### ISSUE THREAD

**Issue by KarsonTheFoxx** [py-mine/mcstatus#274]
Is it possible to get data from a specific scoreboard? in bedrock specifically

**Comment by Iapetus-11** [comment]
One would have to join the server to do that, which is outside the scope of this library currently.

**Comment by kevinkjt2000** [comment]
For now, this is something that mcstatus cannot do. This would require authenticating the protocol connection which will not be implemented anytime soon. It's possible that as [py-mine/PyMine-Net](https://github.com/py-mine/PyMine-Net) evolves that this could be revisited in the future.
