### ISSUE TITLE
Running lookup raises unexpected dns.resolver.NoAnswer error when there's no SRV record for given host

### ISSUE THREAD

**Issue by Errorcrafter** [py-mine/mcstatus#282]
not too sure if this is appropriate here, but attempting to ping, get the status of or query servers using certain server hosts result in `NoAnswer` errors when using both the cli tool and the python implementation. from my testing, the server host most affected by this are shockbyte and minehut.

any help regarding this issue is appreciated

**Comment by kevinkjt2000** [comment]
Providing us with a sample DNS record would be helpful.

**Comment by GStudiosX2** [comment]
> Providing us with a sample DNS record would be helpful.

i know this isnt my issue but this is what i get ```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    server = JavaServer.lookup("playinabox.minehut.gg")
  File "/home/runner/Test2/venv/lib/python3.8/site-packages/mcstatus/server.py", line 57, in lookup
    addr = minecraft_srv_address_lookup(address, default_port=25565, lifetime=timeout)
  File "/home/runner/Test2/venv/lib/python3.8/site-packages/mcstatus/address.py", line 198, in minecraft_srv_address_lookup
    answers = dns.resolver.resolve("_minecraft._tcp." + host, RdataType.SRV, lifetime=lifetime)
  File "/home/runner/Test2/venv/lib/python3.8/site-packages/dns/resolver.py", line 1193, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/runner/Test2/venv/lib/python3.8/site-packages/dns/resolver.py", line 1090, in resolve
    (answer, done) = resolution.query_result(response, None)
  File "/home/runner/Test2/venv/lib/python3.8/site-packages/dns/resolver.py", line 696, in query_result
    raise NoAnswer(response=answer.response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: _minecraft._tcp.playinabox.minehut.gg. IN SRV
```

**Comment by kevinkjt2000** [comment]
It's possible that we could improve documentation in the readme example and possibly catch this exception as a feature, but without an SRV record in the DNS there is no reason to invoke `lookup`. Instead, initializing the class directly would be the thing to do (which maybe lookup could do automatically in the future):
```py
from mcstatus import JavaServer
m = JavaServer("playinabox.minehut.gg")
print(m.status().raw)
```

**Comment by GStudiosX2** [comment]
> It's possible that we could improve documentation in the readme example and possibly catch this exception as a feature, but without an SRV record in the DNS there is no reason to invoke `lookup`. Instead, initializing the class directly would be the thing to do (which maybe lookup could do automatically in the future):
> 
> ```python
> from mcstatus import JavaServer
> m = JavaServer("playinabox.minehut.gg")
> print(m.status().raw)
> ```

i got the code from the python page https://pypi.org/project/mcstatus/ i dont even know how to use this library

**Comment by kevinkjt2000** [comment]
Yeah, that's why I mentioned that the documentation in the readme example could be improved. PyPi's page is generated from the readme file.

**Comment by ItsDrike** [comment]
> It's possible that we could improve documentation in the readme example and possibly catch this exception as a feature, but without an SRV record in the DNS there is no reason to invoke lookup. Instead, initializing the class directly would be the thing to do (which maybe lookup could do automatically in the future):

Actually, `lookup` should never have required the SRV record to pass, it didn't before v9.0.0 and the only reason this is now occurring is because of a change in logic introduced in the Address PR (though already proposed in DNS PR before that). Before that, we were excepting all errors on the resolving function, but after this change, we only started to except `NXDOMAIN` error, not `NoAnswer` ones.

This means that the problem should be quite easy to fix and should just be a manner of adding another exception class (`dns.resolver.NoAnswer`) into the except statement in both `minceraft_srv_address_lookup` function and it's async alternative.

**Comment by kevinkjt2000** [comment]
Upon inspection of the code, it's obvious that we should be handling this as an error.

https://github.com/py-mine/mcstatus/blob/27110dbd73b485ae8c192b92e2e8562c4380c689/mcstatus/address.py#L197-L205

In this code snippet from the `minecraft_srv_address_lookup` function, it's expected that NXDOMAIN was to be received. The docs for https://dnspython.readthedocs.io/en/stable/resolver-class.html#dns.resolver.Resolver.resolve show that NoAnswer could be raised. I'll do a bugfix.

**Comment by ItsDrike** [comment]
> I'll do a bugfix.

@kevinkjt2000 
We should also extend the tests for these functions and simulate `NoAnswer` being raised to avoid this being an issue in the future.

**Comment by kevinkjt2000** [comment]
v9.0.4 is live on PyPi with this fix
