### ISSUE TITLE
Can't acquire online players correctly

### ISSUE THREAD

**Issue by half-nothing** [py-mine/mcstatus#378]
Hi.Yesterday I tried to use mcstatus to acquire server online players.But it reported an error.To be precise, it should be the server side problem.I use the [CatServer](https://github.com/Luohuayu/CatServer) side as the server,and I have already reported the problem to the developers of CatServer.And I've given some specific information in [this](https://github.com/Luohuayu/CatServer/issues/580) issue.
And I will also put some core code here as well.
![image](https://user-images.githubusercontent.com/50048293/185759930-98397ca4-7328-48da-aee4-94987aaf8867.png)
By the way, I have three Minecraft Servers, one is CatServer and the others are pure forge server.Only the CatServer raise exception.

**Comment by kevinkjt2000** [comment]
What error? Which version of mcstatus?

**Comment by half-nothing** [comment]
> What error? Which version of mcstatus?

9.3.0

**Comment by half-nothing** [comment]
> What error? Which version of mcstatus?

Traceback
![image](https://user-images.githubusercontent.com/50048293/185947663-2d1326c1-9c7a-42f7-ba84-a1ef4c64d688.png)

**Comment by half-nothing** [comment]
> What error? Which version of mcstatus?

And another Traceback
![image](https://user-images.githubusercontent.com/50048293/185947819-10926fa3-1134-45cb-95e7-939ebb0c529b.png)

**Comment by kevinkjt2000** [comment]
Could you try again with 9.3.2? There was a fix for #383 that fixed BungeeCord status, maybe CatServer expects the same behavior?

**Comment by half-nothing** [comment]
> Could you try again with 9.3.2? There was a fix for #383 that fixed BungeeCord status, maybe CatServer expects the same behavior?

I have tried version 9.4.1 last night.But unfortunately, the problem still exists.
![image](https://user-images.githubusercontent.com/50048293/187353111-8227d0d9-c645-4762-bea2-d13fc8921291.png)
![image](https://user-images.githubusercontent.com/50048293/187353190-a9f162df-fba0-4812-a710-14ca14ec5d80.png)

**Comment by kevinkjt2000** [comment]
Does the multiplayer screen in a vanilla client show information about a CatServer? Typically `ConnectionRefusedError` is due to a firewall interfering.

**Comment by kevinkjt2000** [comment]
> Show information?I

Yes, when you open the multiplayer list on a client, does the CatServer show information such as MOTD and the server icon?

**Comment by half-nothing** [comment]
> Does the multiplayer screen in a vanilla client show information about a CatServer? Typically `ConnectionRefusedError` is due to a firewall interfering.

I misunderstood your meaning.Multiplayer screen in a vanilla client can show information about a CatServer correctly.
![image](https://user-images.githubusercontent.com/50048293/187448479-4e8c56f3-8ad4-4e21-ad92-d7b15a141b87.png)

**Comment by half-nothing** [comment]
> > Show information?I
> 
> Yes, when you open the multiplayer list on a client, does the CatServer show information such as MOTD and the server icon?

I got a new client.
![image](https://user-images.githubusercontent.com/50048293/187448987-ad750e83-6092-4899-a852-899316a6a295.png)

**Comment by ItsDrike** [comment]
> But unfortunately, althought I fix the mistake,it still didn't work.

Do you still get the same error though? Or do you now see something different?

**Comment by ItsDrike** [comment]
Closing this as stale, if you're still experiencing this problem and want the issue re-opened, just add another comment explaining the second problem you were having. @half-nothing
