### ISSUE TITLE
Playerlist times out on Bungeecord Proxy setups

### ISSUE THREAD

**Issue by LeehamElectronics** [py-mine/mcstatus#407]
I am using Bungeecord and the 
`print(f"Players Online: {', '.join(query.players.names)}")`
Does not work, everything else does. I don't think Bungeecord supports player lists, is there any way around this?
Thanks

**Comment by PerchunPak** [comment]
Did you enable query? Check `query_enabled` in Bungee's config.

**Comment by ItsDrike** [comment]
Could you provide the full traceback of the error, and a minimal reproducable code that demonstrates your issue? It's hard for us to tell what's wrong from just your example print statement.

**Comment by LeehamElectronics** [comment]
`query_enabled` is set to enabled.
Figured it out anyway, I had my port set to the server port instead of the query port, my bad.
![image](https://user-images.githubusercontent.com/51737378/193448441-d71d54d9-4e5b-41d0-9f89-269d8e304b78.png)

Thanks for your help!
