### ISSUE TITLE
Avoid `TYPE_CHECKING` blocks in code

### ISSUE THREAD

**Issue by PerchunPak** [py-mine/mcstatus#420]
As suggested by one of `pyright` maintainers [here](https://github.com/microsoft/pyright/issues/3961#issuecomment-1250333401).

Mostly can be done by resolving #388 and by adding `typing_extensions` to `main` group in `pyproject.toml`.

However, `pyright` actually ignores `TYPE_CHECKING` statement, and checks code as it is without the block. So should we add new dependence? Even if it's quite often in other projects?

**Comment by kevinkjt2000** [comment]
I'm against adding `typing_extensions` as a runtime dependency. Typing is optional in python.
