### ISSUE TITLE
Pinging multiple servers asynchronously gives error. 

### ISSUE THREAD

**Issue by EatJaro** [py-mine/mcstatus#441]
I used a slightly modified version of the code posted by Perchun Pak in issue #436. But I'm getting this error in the console

`RuntimeWarning: coroutine 'JavaServer.async_lookup' was never awaited return RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

And the script only pings one IP over and over again. The full code I used is the same that PerchunPak posted with a different check instead of status.players.max . I do not know why I'm getting this issue if any1 can help. Also sry I cant post exactly my code bcs github code tag is bugging.

**Comment by ItsDrike** [comment]
If you're referring to [this code](https://github.com/py-mine/mcstatus/issues/436#issuecomment-1344021696), then that is not surprising, it's missing another await on this line:

```python
status = await JavaServer.async_lookup(ip).async_status()
```

As you can see, 2 asynchronous functions are called here, yet only one await can be seen. Instead use:
```python
status = await (await JavaServer.async_lookup(ip)).async_status()
# Or, a bit more readable:
server = await JavaServer.lookup(ip)
status = await server.async_status()
```

**Comment by ItsDrike** [comment]
If this resolved your issue, please mark it as closed

**Comment by EatJaro** [comment]
> If you're referring to [this code](https://github.com/py-mine/mcstatus/issues/436#issuecomment-1344021696), then that is not surprising, it's missing another await on this line:
> 
> ```python
> status = await JavaServer.async_lookup(ip).async_status()
> ```
> 
> Here, 2 asynchronous functions are called here, yet only one await can be seen. Instead use:
> 
> ```python
> status = await (await JavaServer.async_lookup(ip)).async_status()
> # Or, a bit more readable:
> server = await JavaServer.lookup(ip)
> status = await server.async_status()
> ```

Thank you that resolved the async issue but it keeps printing `socket.send() raised exception.`. And it still only pings the first couple of servers.

**Comment by EatJaro** [comment]
Sorry accidently closed it

**Comment by EatJaro** [comment]
Im unable to send my complete server list for some privacy reasons but i'll share 20 server ips i want to check
`34.144.241.142
34.111.179.235
34.110.136.32
35.190.14.219
34.160.228.75
156.238.6.241
134.220.157.22
192.56.172.53
134.220.150.23
194.49.28.204
167.235.68.174
134.220.237.11
86.69.8.80
34.117.244.141
34.110.184.92
34.117.151.190
94.24.53.64
192.56.193.169
141.117.158.81
34.160.48.92`

Also each IP is on a newline but github is messing it up and so I also uploaded that to pastebin so here [Test IPS](https://pastebin.com/raw/1VFQwSaR)

And the code I had to post on pastebin bcs github code tag is messed up. [Code](https://pastebin.com/raw/yh2JyGjh)

**Comment by ItsDrike** [comment]
Looking at the code, it seems that you never reset the `to_process` list, which means you keep making repeating requests for the same 16 IPs over and over.

**Comment by PerchunPak** [comment]
> it seems that you never reset the `to_process` list

This means, that you need to add
```py
        to_process = []
```
after
```py
        await asyncio.wait(
            {
                asyncio.create_task(ping_server(ip_to_ping))
                for ip_to_ping in to_process
            }
         )
```
<details>
<summary><b>And it will result to</b></summary>

```py
import asyncio
from inspect import trace
from mcstatus import JavaServer
data = []

async def ping_server(ip: str) -> None:
    try:
        status = await (await JavaServer.async_lookup(ip)).async_status()
    except Exception:
        return

    if status.latency >= 50:
        print(ip)

async def ping_ips(ips: list[str]) -> None:
    to_process: list[str] = []

    for ip in ips:
        if len(to_process) < 16:
            to_process.append(ip)
            continue

        await asyncio.wait(
            {
                asyncio.create_task(ping_server(ip_to_ping))
                for ip_to_ping in to_process
            }
         )
        to_process = []

def main() -> None:
    with open('filtered.txt') as data_:
        for line in data_:
            data.append(line)

    asyncio.run(
        ping_ips(data)
    )


if __name__ == "__main__":
    main()
```

</details>

**Comment by kevinkjt2000** [comment]
@EatJaro I'm absolutely confused on what the intent is of this bit of code:

```python
async def ping_ips(ips: list[str]) -> None:
    to_process: list[str] = []

    for ip in ips:
        if len(to_process) < 16:
            to_process.append(ip)
            continue

        await asyncio.wait(
            {
                asyncio.create_task(ping_server(ip_to_ping))
                for ip_to_ping in to_process
            }
         )
```
Is this adding one `ip` at a time to an array and then repeatedly checking each `ip` that is already in the list additional times for each other `ip` that is added until 16 are in the list? After which the same 16 are checked until `for ip in ips:` completes iterating. Was the intent to create a worker pool that would open a max of 16 connections at a time? Because this is almost certainly not the way to do it.

**Comment by PerchunPak** [comment]
> Is this adding one `ip` at a time to an array and then repeatedly checking each `ip` that is already in the list additional times for each other `ip` that is added until 16 are in the list? After which the same 16 are checked until `for ip in ips:` completes iterating. Was the intent to create a worker pool that would open a max of 16 connections at a time? Because this is almost certainly not the way to do it.

This code forgets to reset `to_process` list. [See my fix](https://github.com/py-mine/mcstatus/issues/441#issuecomment-1350669068).

**Comment by ItsDrike** [comment]
Closing this, as the issue here is a user error, being that the logic in the used script was wrong, not an issue with mcstatus not working correctly.
