### ISSUE TITLE
CI sometimes fails the test_latency_is_real_number

### ISSUE THREAD

**Issue by ItsDrike** [py-mine/mcstatus#442]
The `test_latency_is_real_number` test occasionally fails, indicating that the time difference before sleeping for 1 milisecond, and right after was less than 1 milisecond.

 https://github.com/py-mine/mcstatus/blob/fd03a05c4af6ed57eb9592755e7e52ead2a9ad9d/tests/test_bedrock_status.py#L30-L46

As pointed by @kevinkjt2000, this is likely because of some clock issue with github runners.

Suggested possible fixes:
- Sleep for longer time (3-4 miliseconds)
- Use a tool like [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) to rerun this test if it fails.

Source: [discussion on discord](https://discord.com/channels/936788458939224094/938623566964981802/1052225213733023764)

**Comment by PerchunPak** [comment]
> Use a tool like [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) to rerun this test if it fails.

And not only this, there are a couple of other tests, that often require CI rerun.

**Comment by ItsDrike** [comment]
> And not only this, there are a couple of other tests, that often require CI rerun.

Indeed, though I'm not sure reruns should be a permanent solution to these issues. However to save maintainers some time and avoid confusion for contributors, it could be a good temporary solution.

**Comment by ItsDrike** [comment]
@PerchunPak would you be able to compile a list of all tests that would require reruns?

**Comment by PerchunPak** [comment]
> @PerchunPak would you be able to compile a list of all tests that would require reruns?

Maybe quite later, as I'm really busy on this week.

**Comment by ItsDrike** [comment]
Note: While I did see the comment on #461, saying that this issue shouldn't be resolved with that PR as there might be other functions that need rerunning, I would say that it's simple enough to fix this once it comes up, and this issue was specifically about the latency tests, which are now getting reran.
