### ISSUE TITLE
Crashes if it cannot open `/etc/resolv.conf`

### ISSUE THREAD

**Issue by ShockedCoder** [py-mine/mcstatus#449]
It'd be great if there could default setting in the program or if it let you choose which to file read from.

**Comment by PerchunPak** [comment]
Could you please give traceback and/or more information about the error? Would be awesome if you can reproduce it in docker.

**Comment by PerchunPak** [comment]
In the under hood library, that we use for DNS resolving, this option already is. [See this](https://stackoverflow.com/a/40440766).

So you can use
```py
import mcstatus
import dns.resolver

dns.resolver.default_resolver = dns.resolver.Resolver(configure=False)
dns.resolver.default_resolver.nameservers = ["8.8.8.8"]
server = mcstatus.JavaServer.lookup(...)
```
Note that if your `resolv.conf` doesn't work, something is really wrong. I rarely see an option for configuring custom DNS server only inside application, instead of using system ones.

---

P.S. Without traceback, I cannot be sure that it will help, but you can try.

**Comment by kevinkjt2000** [comment]
Fix your system. Not an mcstatus issue.

**Comment by ShockedCoder** [comment]
I'm using Termux, not a Linux system.

**Comment by ItsDrike** [comment]
We can't support every possible OS and platform, as we have no good ways of testing whether the code works on these platforms, and there's just way too many different platforms to support. We fully support mac os, windows and linux, however if you're using anything else, you're on your own.

As @PerchunPak suggested, there is a workaround which you can use, and if you want to see a better fix for this, report this issue to [`dnspython`](https://github.com/rthalley/dnspython), as mcstatus wouldn't be able to fix this issue anyway. However, I very much doubt that they will add support for Termux, for similar reason to why we won't explicitly support it.

**Comment by PerchunPak** [comment]
There are countless workarounds on Termux for everything.

See https://github.com/termux/termux-packages/issues/1174, https://www.reddit.com/r/termux/comments/rv6vh6/filenotfounderror_errno_2_no_such_file_or/, https://groups.io/g/termux/topic/where_is_etc_resolve_conf/71116836?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,71116836 and finally https://www.google.com/search?q=termux+cannot+open+%2Fetc%2Fresolv.conf
