### ISSUE TITLE
Consider adding a workflow to automatically build the documentation

### ISSUE THREAD

**Issue by ItsDrike** [py-mine/mcstatus#457]
> I wouldn't mind a workflow that automatically checks whether the docs build properly. To speed things up, perhaps it could run only when there are changes in the `/docs` folder, or some similar optimizations.

@ItsDrike 

Readthedocs has this feature. You just need to activate `Build docs on PRs` somewhere on the site.

_Originally posted by @PerchunPak in https://github.com/py-mine/mcstatus/pull/456#discussion_r1064026252_

**Comment by PerchunPak** [comment]
Well, this is just a 5 seconds task...

**Comment by PerchunPak** [comment]
https://user-images.githubusercontent.com/68118654/211188722-a5b3d8e9-86ce-4f21-b152-d5f0d4d2a904.mp4

**Comment by kevinkjt2000** [comment]
https://docs.readthedocs.io/en/stable/pull-requests.html
I checked the box
