### ISSUE TITLE
BedrockServer doesn't support asynchronous call

### ISSUE THREAD

**Issue by timelessnesses** [py-mine/mcstatus#476]
I am trying to build a website where it have minecraft server status using python.  
And I found out that bedrock server doesn't support asynchronous operation at all.  
Is there any that I can achieve like JavaServer does?

**Comment by PerchunPak** [comment]
P.S. This question already in my docs To-Do.

**Comment by ItsDrike** [comment]
> P.S. This question is already in my docs To-Do.

What do you mean? I don't see anything that needs fixing here, I don't think we should provide an `async_lookup` from bedrock servers, because it's simply not needed, bedrock servers don't need any lookup logic that would require async. At most, this can be mentioned in FAQ.

**Comment by PerchunPak** [comment]
> > P.S. This question is already in my docs To-Do.
> > @PerchunPak
> 
> What do you mean? I don't see anything that needs fixing here, I don't think we should provide an `async_lookup` from bedrock servers, because it's simply not needed, bedrock servers don't need any lookup logic that would require async. At most, this can be mentioned in FAQ.

Yes, I meant exactly this ([added](https://github.com/py-mine/mcstatus/compare/0604e0ce57a4cc739a852f044897d847887b5b9a..9086ff3d9484d8cde97d4439741329a1a487017d)).
