### ISSUE TITLE
server.query() always TimeoutError: timed out

### ISSUE THREAD

**Issue by Kevinvincentals** [py-mine/mcstatus#489]
Hello!

Using the example, regardless of what server is put in (And if query is enabled or not), it returns TimeoutError: timed out or "Server did not respond with any information!"

Both server.status and server.ping worwks flawlessly. It only seems to be server.query

Has anyone else had this issue? It also seems to be regardless of behind NAT or not, tried directly without any firewall or anything else in front. 

Tried on mc.hypixel.net, etc

**Comment by ItsDrike** [comment]
Timeout means a connection couldn't be established within some set amout of time. This is likely due to the server not having query enabled. Query is disabled by default, and it needs to be enabled from `server.properties` file, not many publically available servers enable it, and even if they do, query can have different port than the port you connect with.

It could also be that the server is offline, but if status worked, it's likely just not enabled

**Comment by Kevinvincentals** [comment]
> Timeout means a connection couldn't be established within some set amout of time. This is likely due to the server not having query enabled. Query is disabled by default, and it needs to be enabled from `server.properties` file, not many publically available servers enable it, and even if they do, query can have different port than the port you connect with.
> 
> It could also be that the server is offline, but if status worked, it's likely just not enabled.
> 
> You should also try searching for other issues like this

I am aware, however, even servers that I have setup myself, on the edge, without a firewall (And disabled the firewall and or anytthing that could tamper with the connection from the python host), it gives the same errors.

**Comment by Kevinvincentals** [comment]
I was first using sample, but this only displayed 12 usernames.

**Comment by ItsDrike** [comment]
Again, servers need ti have query enabeld in the `server.properties`, if it's not enabled, query obviously won't work, as that minecraft server simply doesn't support it, no matter if that's your server, or a public one

**Comment by Kevinvincentals** [comment]
> Again, servers need to have query enabeld in the `server.properties`, if it's not enabled, query obviously won't work, as that minecraft server simply doesn't have support it, no matter if that's your server, or a public one.

Which is enabled, and the port(s) are open and responding. Same issue.

**Comment by ItsDrike** [comment]
Query port might be different, if you're conected to the server from port `25565`, that doesn't man that a query will be successful, even if it is enabled, as it might be set to use a different port (like `25566`), you'll need to create another `JavaServer` instance with this query port, and use that.

If that doesn't work either, it's some kind of connection issue, it's hard to say but a timeout error isn't something that can be fixed by mcstatus as a library, it's an error during connection establishing raised from `socket`, and simply means the connection failed, as to why, that heavily depends on your network config, etc.

**Comment by Kevinvincentals** [comment]
> Query port might be different, if you're conected to the server from port `25565`, that doesn't mean that a query will be successful, even if it is enabled, as it might be set to use a different port (like `25566`), you'll need to create another `JavaServer` instance with this query port, and use that.
> 
> If that doesn't work either, it's some kind of connection issue, it's hard to say but a timeout error isn't something that can be fixed by mcstatus as a library, it's an error during connection establishing raised from `socket`, and simply means the connection failed, as to why, that heavily depends on your network config, etc.

I will look into the issue further. 
I am indeed using the query port, and not the  server port. it seems to work from other services, in and outside of my own network. 


Thanks for your help though.

**Comment by ItsDrike** [comment]
If the server is public, and you don't mind sharing the IP, it could be worth posting it so we can check whether it works from other machines.

**Comment by Kevinvincentals** [comment]
> If the server is public, and you don't mind sharing the IP, it could be worth posting it so we can check whether it works from other machines.

Sure, no worries.
Game IP: 37.187.137.123:25565
Query: 37.187.137.123:25643

**Comment by ItsDrike** [comment]
Hmm, mcsrvstat.us doesn't seem to be able to even be able to obtain the status info https://mcsrvstat.us/server/37.187.137.123:25565, is the server really running? If so, are you sure this IP is correct? Do you properly handle port forwarding?

**Comment by Kevinvincentals** [comment]
> 

I just figured, that the server is proxied through TCPShield, and thus it may have issues. If I use the SRV record on mcsrvstat, it works completly fine (And fetches all of the users). However, if I use the same srv record in mcstatus, I get TimeoutError: Timed out, so it may have something to do with the proxy.

On the other hand, I figured mcsrvstat can fetch players username without query enabled. They have an API so I may use that :-)

Thanks for your help.

**Comment by Kevinvincentals** [comment]
`The server has 16 player(s) online and replied in 81.300999969244 ms
Traceback (most recent call last):
  File "c:\Users\Kevin\Documents\Python projekter\query-game-servers\test.py", line 16, in <module>
    query = server.query()
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\server.py", line 168, in query
    return self._retry_query(Address(ip, self.address.port))
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\utils.py", line 66, in sync_wrapper
    raise last_exc  # type: ignore # (This won't actually be unbound)
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\utils.py", line 62, in sync_wrapper
    return func(*args, **kwargs)
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\server.py", line 174, in _retry_query
    querier.handshake()
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\querier.py", line 54, in handshake
    packet = self._read_packet()
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\querier.py", line 47, in _read_packet
    packet.receive(self.connection.read(self.connection.remaining()))
  File "C:\Users\Kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mcstatus\protocol\connection.py", line 576, in read
    result.extend(self.socket.recvfrom(self.remaining())[0])
TimeoutError: timed out`

**Comment by ItsDrike** [comment]
> EDIT** Seems like mcsrvstat also only fetches the "sample" of players.

Yeah mcsrvstat can't obtain any more info than mcstatus, all it can do is just make the same request and obtain the server status from that.

> I just figured, that the server is proxied through TCPShield, and thus it may have issues. If I use the SRV record on mcsrvstat, it works completly fine (And fetches all of the users). However, if I use the same srv record in mcstatus, I get TimeoutError: Timed out, so it may have something to do with the proxy.

Can you share the IP address that does work then? If you're concerned about exposing it, feel free to drop me aa DM on discord (ItsDrike#5359)

**Comment by ItsDrike** [comment]
After some further investigation and discussion over discord's DMs, turns out

 Seems like this issue was caused due to the use of TCPShield as a proxy between the actual server (to prevent DDoS attacks), which likely just isn't forwarding UDP traffic.

**Comment by PerchunPak** [comment]
TCPShield includes UDP traffic only in premium plans.
