### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by FewerElk** [py-mine/mcstatus#529]
I'm trying mcstatus. I installed it with pip, but when I import it I've this error : `ImportError: cannot import name 'MinecraftServer' from 'mcstatus'`
At this line : `from mcstatus import MinecraftServer`.
I'm using this project for the repo [https://github.com/PythonInMinecraft/Minecraft-server](https://github.com/PythonInMinecraft/Minecraft-server, branch **net-dev**) (a minecraft server in Python).
**Python 3.11** (64 bits)
**Last version of mcstatus**

**Comment by PerchunPak** [comment]
The `MinecraftServer` was renamed to `JavaServer` in 9.3.1 (#372). Please, refer to [README](https://github.com/py-mine/mcstatus/tree/v10.0.3#readme) or [documentation](https://mcstatus.readthedocs.io/) (added in the next alpha version (11.x.x), so it's not valid for 10.x.x).

To install alpha 11:
```
pip install mcstatus>=11.0.0a3
```

**Comment by ItsDrike** [comment]
Alternatively, you could check out readme for the latest stable version (10.0.3) here: https://github.com/py-mine/mcstatus/tree/v10.0.3 if you don't wish to use the pre-release versions yet.

**Comment by PerchunPak** [comment]
(I linked it in `README` link too)

Also, those pre-releases are pretty stable. We are just just waiting for #335.
