### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by chukfinley** [py-mine/mcstatus#542]
Is there a documentation?
How do I get player list via Server List Ping?
Example code?
Or example code of all options!

Thanks!

**Comment by ItsDrike** [comment]
The documentation for mcstatus is available on https://mcstatus.readthedocs.io/, however the docs were only added pretty recently, and they aren't available for the latest stable release (mcstatus v10.0.3). This is why the linked docs are currently showing a blank page, by default, the docs are configured to track the stable version, and there's no docs for that version available.

If you want to see the newly added documentation, you can click on the version tracker (bottom left) in the docs, and choose the `latest` version (or just go [here](https://mcstatus.readthedocs.io/en/latest/)). This will show you the docs for code that's currently in the `master` branch of this repository.

However, these latest docs are NOT compatible with the v10.0.3 stable release, and so they might be misleading if you're using this version (several functions and attribute names were changed in this release). If you want to, you can already use a release candidate version 11.0.0-rc1, that's already [available on PyPI](https://pypi.org/project/mcstatus/11.0.0rc1/) as a pre-release, and can be installed with `pip install mcstatus==11.0.0rc1`.

If you don't want to use the pre-release, best you can do is check out the README from the v10.0.3 release [here](https://github.com/py-mine/mcstatus/blob/v10.0.3/README.md). For more info about the available functions and attributes, I'd suggest using python's built-in `help` and `dir` functions from REPL. As an example, running `help(mcstatus.JavaServer)` will show you all functions available for the JavaServer class, and a description of what they do pulled directly from the docstrings in the source code, or simply directly checking the source code yourself from [here](https://github.com/py-mine/mcstatus/tree/v10.0.3).

**Comment by ItsDrike** [comment]
(If you have any further questions, please continue in #534, marking this issue as a duplicate)

**Comment by PerchunPak** [comment]
We have a v10 backport of docs. Although, consider it as WIP. 

https://mcstatus.readthedocs.io/en/docs-on-v10/
