### ISSUE TITLE
Not possible to access RawJavaResponse for type annotations

### ISSUE THREAD

**Issue by CoolCat467** [py-mine/mcstatus#554]
Because everything is closed off in `__init__.py` with the `__all__` declaration, it does not seem to be possible to access the `status_response` module, which has the `RawJavaResponse`, which I need for type annotations in a program I'm writing.

**Comment by CoolCat467** [comment]
that'll teach me not to complain without checking if the new release is out yet

Sorry about that

**Comment by PerchunPak** [comment]
Also, be aware that this is not a part of public API. You can access everything, `__all__` just shows what is expected to be used.
