### ISSUE TITLE
can i execute commands

### ISSUE THREAD

**Issue by mncrftfrcnm** [py-mine/mcstatus#831]
can i execute commands like /say?

**Comment by ItsDrike** [comment]
No, mcstatus only provides the response from a status packet, i.e. what you would see in the multiplayer server list. There's also support for query protocol, which can be used to get some other data about the server, but neither of these allow for execution of commands.

To do that, you would need to actually have a user login into the server and run this command, or use rcon and access the server's console remotely, both of these are out of scope of mcstatus.

**Comment by mncrftfrcnm** [comment]
thank you for your answer, @ItsDrike.
