### ISSUE TITLE
AttributeError when CLI is called with only one argument

### ISSUE THREAD

**Issue by katrinafyi** [py-mine/mcstatus#846]
For example:
```bash
$ mcstatus anything
Traceback (most recent call last):
  File "bin/.mcstatus-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "lib/python3.12/site-packages/mcstatus/__main__.py", line 100, in main
    args.func(server)
    ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'func'
```
I assume this is because of the subparser logic in: https://github.com/py-mine/mcstatus/blob/be6e71ab887e0aafcd2c6a8efdd9962da9d714ea/mcstatus/__main__.py#L84-L88

A reasonable solution might be to default to the `status` subcommand. Otherwise, a more friendly error would also make sense.

This is mcstatus-11.1.1.

**Comment by katrinafyi** [comment]
I for one would like to use the CLI :) I don't know of any other command-line tools which could replace it.

**Comment by PerchunPak** [comment]
> I for one would like to use the CLI :) I don't know of any other command-line tools which could replace it.

There are `curl ... | jq` where `...` can be https://statusmc.perchun.it, https://mcstatus.io, https://mcsrvstat.us, but that is not what you're looking probably.

> I could even look into a rewrite if you'd like.

Yeah, sure. Note that you can do whatever you want with output of CLI, we already have a few breaking changes in main and CLI absolutely needs another one.

**Comment by katrinafyi** [comment]
I'm interested in checking a LAN server which the online sites can't reach, I think the CLI has an important use here.

**Comment by katrinafyi** [comment]
I have a fix for this bug and support for Bedrock in this fork: https://github.com/rina-forks/mcstatus/tree/cli-rewrite. 

I'm actually not sure what else you'd like changed. Looking at the code, aside from some minor repetition, it looks mostly okay to me. Some things could be rearranged, like moving JSON encoding into the Response classes, and host IP/port into proper fields?

**Comment by ItsDrike** [comment]
I think it doesn't hurt us to keep the CLI, but I do agree that a rewrite would be nice there. If we'll go with the rewrite, I'd suggest using the https://typer.tiangolo.com/ library.

**Comment by PerchunPak** [comment]
`typer` is a really good library, but I want to remind, that we had many problems when used external library for CLI. We should stick to `argparser`

**Comment by ItsDrike** [comment]
> but I want to remind, that we had many problems when used external library for CLI

Like what?

**Comment by PerchunPak** [comment]
> I have a fix for this bug and support for Bedrock in this fork: https://github.com/rina-forks/mcstatus/tree/cli-rewrite.

Open a PR, we will discuss it properly there
